export enum SecurityErrorMessage {

    BAD_CREDENTIALS = "BAD_CREDENTIALS",

    INSUFFICIENT_AUTH = "INSUFFICIENT_AUTH",

    USER_DISABLED = "USER_DISABLED",

    USER_BLOCKED = "USER_BLOCKED",

    UNKNOWN_SECURITY_ERROR = "UNKNOWN_SECURITY_ERROR"
}